/**
 * Seed list of plumbing service categories. Stored in the DB (`ServiceCategory`
 * table) so admins can edit/add/deactivate without a deploy — this constant
 * is only the seed data + a shared slug type for the Phase-1 forms.
 */
export const SERVICE_CATEGORY_SEEDS = [
  {
    slug: "emergency-leak",
    name: "Emergency leak",
    description: "Active water leak causing ongoing damage.",
    emergencyEligible: true,
    pricingMethod: "diagnostic_then_estimate" as const,
    baseDiagnosticFeeCents: 8_900,
    estimatedRangeCents: [15_000, 60_000] as [number, number],
  },
  {
    slug: "burst-pipe",
    name: "Burst pipe",
    description: "Pipe has ruptured; water supply may need immediate shutoff.",
    emergencyEligible: true,
    pricingMethod: "diagnostic_then_estimate" as const,
    baseDiagnosticFeeCents: 8_900,
    estimatedRangeCents: [20_000, 80_000] as [number, number],
  },
  {
    slug: "clogged-drain",
    name: "Clogged drain",
    description: "Slow or blocked drain in a sink, shower, or floor drain.",
    emergencyEligible: false,
    pricingMethod: "fixed" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [12_000, 30_000] as [number, number],
  },
  {
    slug: "blocked-toilet",
    name: "Blocked toilet",
    description: "Toilet is clogged or not flushing properly.",
    emergencyEligible: true,
    pricingMethod: "fixed" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [12_000, 28_000] as [number, number],
  },
  {
    slug: "faucet-repair",
    name: "Faucet repair",
    description: "Leaking, dripping, or broken faucet.",
    emergencyEligible: false,
    pricingMethod: "hourly" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [10_000, 25_000] as [number, number],
  },
  {
    slug: "sink-repair",
    name: "Sink repair",
    description: "Sink leaks, drainage issues, or installation.",
    emergencyEligible: false,
    pricingMethod: "hourly" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [10_000, 30_000] as [number, number],
  },
  {
    slug: "toilet-repair-install",
    name: "Toilet repair or installation",
    description: "Repair or install a toilet.",
    emergencyEligible: false,
    pricingMethod: "fixed" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [15_000, 45_000] as [number, number],
  },
  {
    slug: "shower-bathtub-repair",
    name: "Shower or bathtub repair",
    description: "Leaks, drainage, or fixture issues in a shower or bathtub.",
    emergencyEligible: false,
    pricingMethod: "hourly" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [15_000, 50_000] as [number, number],
  },
  {
    slug: "water-heater-issue",
    name: "Water heater issue",
    description: "No hot water, leaking tank, or water heater failure.",
    emergencyEligible: true,
    pricingMethod: "diagnostic_then_estimate" as const,
    baseDiagnosticFeeCents: 8_900,
    estimatedRangeCents: [20_000, 150_000] as [number, number],
  },
  {
    slug: "sump-pump-issue",
    name: "Sump pump issue",
    description: "Sump pump failure or flooding risk.",
    emergencyEligible: true,
    pricingMethod: "diagnostic_then_estimate" as const,
    baseDiagnosticFeeCents: 8_900,
    estimatedRangeCents: [20_000, 90_000] as [number, number],
  },
  {
    slug: "pipe-repair",
    name: "Pipe repair",
    description: "General pipe repair not covered by burst pipe or leak.",
    emergencyEligible: false,
    pricingMethod: "diagnostic_then_estimate" as const,
    baseDiagnosticFeeCents: 8_900,
    estimatedRangeCents: [15_000, 60_000] as [number, number],
  },
  {
    slug: "appliance-hookup",
    name: "Appliance hookup",
    description: "Connect a dishwasher, washing machine, or fridge water line.",
    emergencyEligible: false,
    pricingMethod: "fixed" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [12_000, 35_000] as [number, number],
  },
  {
    slug: "drain-cleaning",
    name: "Drain cleaning",
    description: "Preventive or deep drain cleaning.",
    emergencyEligible: false,
    pricingMethod: "fixed" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [15_000, 40_000] as [number, number],
  },
  {
    slug: "plumbing-inspection",
    name: "Plumbing inspection",
    description: "General inspection, e.g. for a home purchase.",
    emergencyEligible: false,
    pricingMethod: "fixed" as const,
    baseDiagnosticFeeCents: 0,
    estimatedRangeCents: [15_000, 35_000] as [number, number],
  },
  {
    slug: "other",
    name: "Other plumbing problem",
    description: "Doesn't fit another category — describe the issue.",
    emergencyEligible: true,
    pricingMethod: "diagnostic_then_estimate" as const,
    baseDiagnosticFeeCents: 8_900,
    estimatedRangeCents: [10_000, 100_000] as [number, number],
  },
];

export type ServiceCategorySlug = (typeof SERVICE_CATEGORY_SEEDS)[number]["slug"];
